// SPDX-License-Identifier: CC0-1.0
pragma solidity ^0.8.24;

// AUTOGENERATED by build/gen_solidity.py — do not edit by hand.
// Mirrors build/out/manifest.json (the verified encoding).
library DinoData {
    uint256 internal constant SUPPLY = 10001;
    uint256 internal constant N_COMPOSITE = 105;
    uint256 internal constant N_UNIQUE = 16;
    uint256 internal constant TOKEN_BYTES = 5;

    function widths() internal pure returns (uint8[9] memory w) {
        w[0] = 5; // background
        w[1] = 5; // body
        w[2] = 4; // spikes
        w[3] = 4; // chest
        w[4] = 2; // feet
        w[5] = 2; // hands
        w[6] = 4; // head
        w[7] = 3; // face
        w[8] = 4; // eyes
    }

    function catBase() internal pure returns (uint16[9] memory b) {
        b[0] = 0; // background
        b[1] = 22; // body
        b[2] = 41; // spikes
        b[3] = 55; // chest
        b[4] = 66; // feet
        b[5] = 70; // hands
        b[6] = 74; // head
        b[7] = 85; // face
        b[8] = 92; // eyes
    }

    function orderCount() internal pure returns (uint256) { return 5; }

    function order(uint256 id) internal pure returns (uint8[9] memory o) {
        if (id == 0) {
            // background > body > spikes > chest > feet > hands > eyes > face > head
            o[0] = 0;
            o[1] = 1;
            o[2] = 2;
            o[3] = 3;
            o[4] = 4;
            o[5] = 5;
            o[6] = 8;
            o[7] = 7;
            o[8] = 6;
        }
        else if (id == 1) {
            // background > body > spikes > chest > feet > hands > face > head > eyes
            o[0] = 0;
            o[1] = 1;
            o[2] = 2;
            o[3] = 3;
            o[4] = 4;
            o[5] = 5;
            o[6] = 7;
            o[7] = 6;
            o[8] = 8;
        }
        else if (id == 2) {
            // background > body > spikes > chest > feet > hands > head > eyes > face
            o[0] = 0;
            o[1] = 1;
            o[2] = 2;
            o[3] = 3;
            o[4] = 4;
            o[5] = 5;
            o[6] = 6;
            o[7] = 8;
            o[8] = 7;
        }
        else if (id == 3) {
            // background > body > spikes > chest > feet > hands > head > face > eyes
            o[0] = 0;
            o[1] = 1;
            o[2] = 2;
            o[3] = 3;
            o[4] = 4;
            o[5] = 5;
            o[6] = 6;
            o[7] = 7;
            o[8] = 8;
        }
        else if (id == 4) {
            // background > body > spikes > chest > feet > head > face > eyes > hands
            o[0] = 0;
            o[1] = 1;
            o[2] = 2;
            o[3] = 3;
            o[4] = 4;
            o[5] = 6;
            o[6] = 7;
            o[7] = 8;
            o[8] = 5;
        }
    }

    function attrOrderIdx() internal pure returns (uint8[9] memory a) {
        a[0] = 0; // background
        a[1] = 1; // body
        a[2] = 3; // chest
        a[3] = 8; // eyes
        a[4] = 7; // face
        a[5] = 4; // feet
        a[6] = 5; // hands
        a[7] = 6; // head
        a[8] = 2; // spikes
    }

    function traitType(uint256 cat) internal pure returns (string memory) {
        return _at("background\nbody\nspikes\nchest\nfeet\nhands\nhead\nface\neyes", cat);
    }

    function catValue(uint256 cat, uint256 id) internal pure returns (string memory) {
        if (cat == 0) return _at("blue\nblue conical gradient\nblue linear gradient\nday landscape\ngray\ngreen\ngreen conical gradient\nlight brown\nlight gray\nnight landscape\norange\norange conical gradient\npink\npink linear gradient\npurple\npurple conical gradient\npurple linear gradient\nred conical gradient\nred linear gradient\nsnow landscape\nyellow\nyellow linear gradient", id);
        else if (cat == 1) return _at("aqua\nblue\nblue linear gradient\ngray\ngrayspace linear gradient\ngreen\ngreen linear gradient\nlight green\nlime green\norange linear gradient\npink\npink linear gradient\npurple\npurple linear gradient\nrainbow\nred\nteal\nyellow\nyellow linear gradient", id);
        else if (cat == 2) return _at("blue\nburnt orange\ndark gray\ngreen\nlight gray\nmulticolor\nnone\norange\npink\npurple\nred\nteal\nwhite\nyellow", id);
        else if (cat == 3) return _at("aqua\nblue\ngray\ngreen\nlight blue\nlight gray\norange\norangered\npink\npurple\nyellow", id);
        else if (cat == 4) return _at("hoverboard\nnormal\nrocket boots\nskateboard", id);
        else if (cat == 5) return _at("cast left\ncast right\nkite\nnormal", id);
        else if (cat == 6) return _at("bandana\ncap backwards\ncap forwards\nchef\ncrown\nheadphones\nlong peak cap forwards\nmouse ears\nnone\nsilly yellow\ntwo tone cap backwards", id);
        else if (cat == 7) return _at("bandages\nmask\nninja\nnormal\nnoun glasses\nskull\nvizor", id);
        else if (cat == 8) return _at("blue\nblue yellow\ndark gray\ndark red\ngreen\ngreen red\nlazer\nlight gray\norange\npurple\nred\nwhite\nyellow", id);
        revert("cat");
    }

    function mintedOn(uint256 id) internal pure returns (string memory) {
        return _at("arb\navax\nbsc\neth\nftm\nopt\npoly", id);
    }

    function oneOfOne(uint256 id) internal pure returns (string memory) {
        return _at("arb\navax\nbsc\nbug\ncryptoad\neth\nfriendly dino\nftm\nghost\nmfer\nopt\npoly\nrapter\nrexx\nsmol birb\nxoshi", id);
    }

    // Returns the idx-th '\n'-delimited field of `blob`.
    function _at(string memory blob, uint256 idx) private pure returns (string memory) {
        bytes memory b = bytes(blob);
        uint256 start = 0;
        uint256 field = 0;
        for (uint256 i = 0; i <= b.length; i++) {
            if (i == b.length || b[i] == 0x0a) {
                if (field == idx) {
                    bytes memory out = new bytes(i - start);
                    for (uint256 j = start; j < i; j++) out[j - start] = b[j];
                    return string(out);
                }
                field++;
                start = i + 1;
            }
        }
        revert("idx");
    }
}
